
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - defense.security.cn
  resources:
  - honeypots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - defense.security.cn
  resources:
  - honeypots/finalizers
  verbs:
  - update
- apiGroups:
  - defense.security.cn
  resources:
  - honeypots/status
  verbs:
  - get
  - patch
  - update
