apiVersion: defense.security.cn/v1
kind: Honeypot
metadata:
  name: honeypot-sample
spec:
  # Add fields here
  clusterKey: abcd122
  service: aaaaaa-svc
  workload: bbbbbb-deploy
  image: docker.io/kennethreitz/httpbin
  workloadPort: 80
  servicePort: 8000
