apiVersion: defense.security.cn/v1
kind: Honeypot
metadata:
  name: honeypot-sample
spec:
  # Add fields here
  clusterKey: abcd122
  service: aaaaaa-svc
  workload: bbbbbb-deploy
  image: docker.io/kennethreitz/httpbin
  ports:
  - port: 8000
    targetPort: 80
  - port: 6437
    targetPort: 6437
  secrets:
  - username: robbie
    password: abdee
    server: harbor.abc.com